### ISSUE TITLE
Project staus

### ISSUE THREAD

**Issue by peter279k** [dwightwatson/colortime#1]
Firstly, thank you for this color time.

And I plan to use the package in my customized console.

I find that this project has not updated commit for about five years.

Is project still alive?

Thanks.

**Comment by dwightwatson** [comment]
It's alive as much as it needs to be - it's a very simple class and doesn't really require any work.

I can't remember what I originally built it for, but I'm unlikely to make any changes to it because it doesn't need any.

So if you intend to use it as-is then go nuts, if you were hoping for more functionality you'd be better off copying the code and doing your own thing with it.
